### ISSUE TITLE
✨ theme hook similar to useColorMode in bootstrap-vue-next

### ISSUE THREAD

**Issue by huseeiin** [sveltestrap/sveltestrap#33]
**Is your feature request related to a problem? Please describe.**
it can be a pain in the ass to configure all of dark, light and system detect theme modes on your own. a library like bootstrap-vue-next simplifies this with a simple bootstrap-specific hook: `useColorMode`
see: https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/composables/useColorMode.html

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dysfunc** [comment]
Thanks for submitting a feature request @xxxhussein! I've been working on a theme provider for wrapping your entire app or individual components, and several theme utility methods. 

These are all of the things I have working on my local dev:

**Global**
Using wrapper:
```svelte
<script>
  import { Theme } from '@sveltestrap/sveltestrap';
</script>

<Theme theme="dark">
   <App.../>
</Theme>
```

Using store:
```svelte
<script>
  import { colorMode } from '@sveltestrap/sveltestrap';

  const toggleTheme = () => {
    $colorMode = $colorMode === 'dark' ? 'light' : 'dark';
  };
</script>

<button on:click={toggleTheme}>Toggle Theme</button>
```

**Scoped**
Using wrapper:
```svelte
<script>
  import { Theme } from '@sveltestrap/sveltestrap';
</script>

<div>
  <Theme theme="dark">
    <Alert ...>
  </Theme>
  <Theme theme="light">
    <Alert ...>
  </Theme>
</div>
``` 
Using prop:
```svelte
<Alert theme="light" />
```
