### ISSUE TITLE
🐛 Event handler types are broken

### ISSUE THREAD

**Issue by vostrnad** [sveltestrap/sveltestrap#39]
**Describe the bug**
Every time I try to attach an event handler to a Sveltestrap component, TypeScript throws this weird error:
```
Argument of type 'string' is not assignable to parameter of type 'never'.
```
The actual event handler works fine, this is purely a type issue.

**How to reproduce**
```svelte
<Input on:input={(e) => console.log(e)} />
<!--      ^^^^^ Error is here          -->
```

**Comment by dysfunc** [comment]
I think we have two options:

1. We can explicitly define all input event types 

```js
export interface InputEvents {
  blur: Event;
  click: MouseEvent;
  change: Event;
  focus: Event;
  input: Event;
  keydown: KeyboardEvent;
  keypress: KeyboardEvent;
  keyup: KeyboardEvent;
  mousedown: MouseEvent;
  mouseup: MouseEvent;
  ...
}
```

2. We just include all input events

```js
export interface InputEvents {
  [key: string]: Event;
}
```

**Comment by vostrnad** [comment]
Since these event types exist on standard HTML elements (where they seem to work fine) I'd think it should be possible to just import those types?

**Comment by Nate561** [comment]
As mentioned in Issues channel on Slack, I found that `ListGroupItems` also gives a TS error when attempting to use the `on:click` event. The event handler still works correctly and seems to be a type issue as well.
