### ISSUE TITLE
Incorrect types  🐛 

### ISSUE THREAD

**Issue by rallets** [sveltestrap/sveltestrap#43]
**Describe the bug**
Hi, I'm migrating from sveltestrap, and I found some inconsistency with the new library and the event type definition emitted by Input.

**How to reproduce**
<Input type="textarea" on:input="{(x) => console.log(x.currentTarget?.value)}" />

raises an error:
`Property 'value' does not exist on type 'EventTarget'.ts(2339)`

<AccordionItem on:toggle="{(e) => doSomething(e.detail)}">
raises an error:
`Argument of type 'void' is not assignable to parameter of type 'boolean'.ts(2345)`

**Expected behavior**
In my opinion `currentTarget` should not be nullable (as it's the element triggering the event), and should be of a `HTMLInputElement` type instead of a generic `EventTarget`.

`e.detail` was of type `boolean` in sveltestrap.

**Additional context**
VSCode 1.85.1

Now I'm also wondering if this are only type definition changes between the two libraries, or also the behavior has changed? do you have a list of `braking changes` ?

Thank you for taking care of this library.

**Comment by dysfunc** [comment]
Hey @rallets, apologies for the late reply. The `<Input>` component is more or less the same as it was before. 

**Before**
https://github.com/bestguy/sveltestrap/blob/master/src/Input.d.ts

**After**
https://github.com/sveltestrap/sveltestrap/blob/main/src/Input/Input.d.ts

The event objects are also identical to the DOM event bindings
https://svelte.dev/repl/ebb44602fa604d029cfcf26642a71e28?version=4.2.9

**Comment by rallets** [comment]
Hi, I think I did not explain myself correclty. Attached you can find two screenshot from VS Code showing the type definition for the `onclick` event, one for sveltestrap and one for native svelte. As you can see, sveme has a correct event type definition for `currentTarget: EventTarget & HTMLInputElement` instead of your `Event.currentTarget: EventTarget | null`

![sveltestrap input onclick event](https://github.com/sveltestrap/sveltestrap/assets/379999/46a8c150-cc36-4082-8ede-24d977e39a78)

![svelte input onclick event](https://github.com/sveltestrap/sveltestrap/assets/379999/3a3f2207-6e6a-4fa3-98de-8616f14be635)

**Comment by rallets** [comment]
Sveltestrap 5.11.2 had instead `any` and that allowed to write code like `event.currentTarget.value` without errors in VS Code. Th e problem is that is not possible to write inline code like (see attachment)
```
 on:click="{(e) => {
    const currentTarget = e.currentTarget as HTMLInputElement;
    e.currentTarget && console.log(currentTarget.value)
}}"
```
because VS Code Eslint complains about `Unexpected token`.

![sveltestrap input onclick event - casting](https://github.com/sveltestrap/sveltestrap/assets/379999/f270b96a-2ec2-4507-8fc0-f94b75f9c866)

**Comment by dysfunc** [comment]
@rallets does the PR resolve your issues?

**Comment by dysfunc** [comment]
you could fork this and pull down my branch or just replace the contents of the types def of the installed package with the changes in the PR

**Comment by rallets** [comment]
Hi, so the input type `textarea`, `text`, `number`, `select`, `date` are working well for the "standard" events, but some improvements could be made:
- input type `checkbox` should have a `event.currentTarget.checked` property
- input type `number` should have a `valueAsNumber` property
- input type `date` should have a `valueAsDate` property
- `Input` itself should have also a `mousedown` event

**Comment by dysfunc** [comment]
Try the latest changes. This should address everything mentioned in this thread

**Comment by rallets** [comment]
Hi, I tried the latest but I get for each event type `any`. So I digged a little bit, and found that `Input.d.ts` give me some errors:
````
Interface 'InputProps' cannot simultaneously extend types 'HTMLInputAttributes' and 'HTMLSelectAttributes'.
  Named property ''on:abort'' of types 'HTMLInputAttributes' and 'HTMLSelectAttributes' are not identical.ts(2320)
```
and
```
Generic type 'InputElementEvent' requires 3 type argument(s).ts(2314)
type InputElementEvent<T extends HTMLInputElement, HTMLSelectElement, HTMLTextAreaElement> = Event & {
    currentTarget: T;
    target: T;
}
```

![image](https://github.com/sveltestrap/sveltestrap/assets/379999/fbfec556-3c45-438f-bc30-b0faaaeb2638)

**Comment by dysfunc** [comment]
PR updated. I'm not seeing any of the errors locally now.

**Comment by dysfunc** [comment]
We can use this ticket

**Comment by dysfunc** [comment]
new PR up https://github.com/sveltestrap/sveltestrap/pull/57

**Comment by rallets** [comment]
Many thanks @dysfunc , it works like a charm 👍

**Comment by dysfunc** [comment]
Released https://github.com/sveltestrap/sveltestrap/releases/tag/v6.2.4
