### ISSUE TITLE
✨ Positioned badges support

### ISSUE THREAD

**Issue by planetsLightningArrester** [sveltestrap/sveltestrap#44]
**Is your feature request related to a problem? Please describe.**
[I saw in the docs](https://sveltestrap.js.org/?path=/docs/components-badges--docs) that sveltstrap supports Badges, but I couldn't find [Positioned Badges](https://getbootstrap.com/docs/5.3/components/badge/#positioned). They were added in Bootstrap v5. Is there support for it?

**Describe the solution you'd like**
I'd like to know if there's support for it or plans to support it. If they are supported, they are not in the docs.

**Describe alternatives you've considered**
I tried to use it with the example below, and it seems supported. So, it could be missing in the docs. Although this is not strictly a component implementation, it seems to follow Bootstrap's docs.
```svelte
      <Container>
          <Row>
            <Col>
              <p class="position-relative">
                <b>Title</b>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                  99+
                  <span class="visually-hidden">unread messages</span>
                </span>
              </p>
            </Col>
          </Row>
      </Container>
```

**Additional context**
Positioned badges examples
<img width="87" alt="image" src="https://github.com/sveltestrap/sveltestrap/assets/52364115/fbbce4c4-bca0-4614-bdbe-10a8a4286212">
<img width="85" alt="image" src="https://github.com/sveltestrap/sveltestrap/assets/52364115/6c3dacd3-249c-4db8-8c4e-e14e30452d92">

Thank you!

**Comment by dysfunc** [comment]
Hey @planetsLightningArrester! Thanks for submitting the feature request. We have not modified the badge to component to simplify positioned badges, but this is something I can add to the roadmap. In the meantime, you can still use positioned badges with the library https://svelte.dev/repl/65bbd1777aab4715b47389a60fa02f5d?version=4.2.8
