### ISSUE TITLE
🐛 Input with reactive statement causes infinite loop in SSR

### ISSUE THREAD

**Issue by vostrnad** [sveltestrap/sveltestrap#47]
**Describe the bug**
The component below causes SvelteKit to enter an infinite loop and eventually run out of memory when rendered on a server (i.e. during initial page load). If the component is rendered on the client (e.g. during client-side navigation) it works completely fine. I tried my best to reproduce it with a plain `<input>` or `<select>` element and failed, which leads me to believe this is a bug in Sveltestrap, not an issue with SvelteKit itself.

**How to reproduce**
```svelte
<script lang="ts">
  import { Input } from '@sveltestrap/sveltestrap'

  let checked = false
  let value: string | undefined

  $: if (!checked) {
    console.log('Setting value to undefined')
    value = undefined
  }
</script>

<input type="checkbox" bind:checked />

<Input type="select" disabled={!checked} bind:value>
  <option value="one">One</option>
  <option value="two">Two</option>
</Input>
```

Note that the checkbox isn't actually needed to reproduce the issue, just this is enough to trigger it:
```svelte
<script lang="ts">
  import { Input } from '@sveltestrap/sveltestrap'

  $: value = undefined
</script>

<Input bind:value />
```

**Comment by dysfunc** [comment]
I can look at this more tomorrow, but it appears to work fine if you use an empty string v `undefined` to reset the value. Setting `undefined` throws it into a loop and crashes.

**Comment by dysfunc** [comment]
After spending a decent amount of time debugging this, it appears to be an issue with SvelteKit and not Sveltestrap. I even went to the extent of removing all bindings from the `<Input>` component,nd simplifying the component structure to the bare minimum, essentially using plain HTML. The problem persists regardless of bindings or component structure.

If this were a Sveltestrap issue, I would expect this to happen regardless of environment at the component level. I'll open a ticket up and see what they say.

https://svelte.dev/repl/dc06701079374ddcbb60432cb8592ed3?version=4.2.8

**Comment by vostrnad** [comment]
Can you link the SvelteKit issue when it's opened?

**Comment by dysfunc** [comment]
Yes, I will. This was bugging me so I tried debugging again, and I found the issue is related to the default value. I can reproduce it with the most basic component wrapping any input element. The PR should fix issues with Sveltestrap bindings, but something the SvelteKit team will need to look at.

**Comment by dysfunc** [comment]
If you wouldn't mind, could you please pull the latest and confirm the issue gone.

**Comment by vostrnad** [comment]
Looks good now, thanks!
