### ISSUE TITLE
Type script error for Button with target property.🐛 

### ISSUE THREAD

**Issue by StagnantIce** [sveltestrap/sveltestrap#50]
export interface ButtonProps extends HTMLButtonAttributes {

Maybe need replace to

export interface ButtonProps extends HTMLButtonAttributes | HTMLLinkAttributes {

**Comment by StagnantIce** [comment]
Thank you, its works, but you have problem there with ButtonColor property, its not imported

**Comment by dysfunc** [comment]
That's fixed. It'll be out in the next patch release 6.2.3
