### ISSUE TITLE
🐛 Set type='number' in Input component produces string value

### ISSUE THREAD

**Issue by aperture147** [sveltestrap/sveltestrap#60]
**Describe the bug**
Set `<Input type="number">` in `Input` component still produces string value.
This problem does not happen with default HTML `input`
**How to reproduce**

```svelte
<script lang='ts'>
	import { Input } from '@sveltestrap/sveltestrap';
	let a = 1;
	let b = 1;
</script>
<p>change the value of boxes below</p>
<label>
	a <input type="number" bind:value={a} min="0" max="10" />
</label>
<br>
<label>
	b <Input type="number" bind:value={b} min="0" max="10" />
</label>

<p>type of a: {typeof a}</p>
<p>type of b: {typeof b}</p>
```

result: 
type of a: `number`
type of b: `string`

REPL: [click here](https://svelte.dev/repl/e8ec909c241b44dbba252d07b27e734b?version=4.2.12)

**Expected behavior**
value should be `number`, not `string`

**Screenshots**
![Screenshot 2024-02-23 at 5 53 51 PM](https://github.com/sveltestrap/sveltestrap/assets/32543264/8db3b11a-52dc-4528-ac7a-46c73604767d)

**Desktop (please complete the following information):**

- OS: macOS Sonoma 14.3.1
- Browser: Chrome, Firefox, Safari
- Version: Svelte 4, Sveltestrap 6.2.5

**Additional context**
This problem didn't occur with sveltestrap in `bestguy/sveltestrap`

**Comment by dysfunc** [comment]
Thank you @aperture147 for submitting an issue! 

Please confirm that the changes in #61 fix your issue.

**Comment by aperture147** [comment]
Thanks. I'm sorry but how can I install it from git? I tried `npm i https://github.com/sveltestrap/sveltestrap/tarball/fix-input-num-range-values` but it failed to build.

**Comment by dysfunc** [comment]
You could pull fork the repo and pull the branch down or replace the content of `node_modules/@sveltestrap/sveltestrap/dist/input.svelte` with these changes and then restart your app so it can bundle the latest changes.

**Comment by aperture147** [comment]
Thanks, I've tested by replacing the `Input.svelte` file and it works now!

**Comment by rallets** [comment]
Hi @dysfunc I'm also affected by this small bug. Thanks to have fixed it. Do you have an estimated date for a new release?

**Comment by dysfunc** [comment]
released https://github.com/sveltestrap/sveltestrap/releases/tag/v6.2.6
