### ISSUE TITLE
✨ Tooltip delay

### ISSUE THREAD

**Issue by irt-msummers** [sveltestrap/sveltestrap#65]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use data-bs-delay to set the show and hide (eg {"show":1500,"hide":200})

**Describe the solution you'd like**
I would like show and hide as props for the Tooltip

<img width="489" alt="image" src="https://github.com/sveltestrap/sveltestrap/assets/1631628/dfed4c7a-2e0d-4dca-a203-051a6d9b60d5">

I would just like these to open slower if you are moving your mouse so they don't if they are not looking for info

Thanks

**Comment by dysfunc** [comment]
This is now supported using the `delay` prop on the `<Tooltip />` component. It was released in `6.2.7`

**Comment by irt-msummers** [comment]
Thanks so much for the quick fix.  It seems to work for most cases but that Inventory one opens a modal and then when it closes it pops up and I wasn't leaving the cursor on top of it.


<img width="465" alt="image" src="https://github.com/sveltestrap/sveltestrap/assets/1631628/beddf109-1649-43f7-bea0-9895eb741d33">
<img width="1662" alt="image" src="https://github.com/sveltestrap/sveltestrap/assets/1631628/17127682-9ad3-4e87-b8f2-63d7202da04d">

`function inventory() {`
 ` showInventory = true;`
`}`


`<NavItem>`
        `<NavLink id="nav-inventory" on:click={inventory} href={'#'}>`
          `<Icon class="fs-4 mb-3" name="journals" />`
       ` </NavLink>`
      `</NavItem>`
      `<Tooltip delay={DELAY} target="nav-inventory" placement="bottom">Inventory</Tooltip>`


`{#if showInventory}`
` <container>`
`<Modal class="modal-lg window" isOpen={true} >`
`  <ModalHeader class="modal-header window" {toggle}></ModalHeader>`
`    <ModalBody >`
`        <iframe src="/tables/inventory?window"  scrolling="no" style=" width: 100%; height: 610px;  overflow: hidden;" ></iframe>`
`    </ModalBody>`
   
`</Modal>`
`</container>`
`{/if}`

**Comment by dysfunc** [comment]
I can't reproduce that issue. https://svelte.dev/repl/hello-world?version=4.2.12

**Comment by irt-msummers** [comment]
https://svelte.dev/repl/8c14145bd09d45e79c98687af8c7fd41?version=4.2.12

And I see it Chrome but not Safari

**Comment by dysfunc** [comment]
It works in Chrome, Safari, Edge, Opera, Brave, and Firefox for me. Which version of Chrome are you running? 

This is Chrome:
https://www.loom.com/share/479e936efe1e46a2bf5339e7fd4238c4?sid=5f8cea77-f026-451e-a718-ba2d8bb3dc22

**Comment by irt-msummers** [comment]
I just tested on my Win11 VM with Chrome (no extensions -- not logged in) and Edge and it does it there too

**Comment by dysfunc** [comment]
https://github.com/sveltestrap/sveltestrap/assets/1918732/55405b6e-c775-421f-9deb-ed9371e735f3

**Comment by irt-msummers** [comment]
So do what I did just quickly click the link and then click the button above test does Inventory come up

**Comment by dysfunc** [comment]
Oh, interesting. This isn't actually related to the `<Tooltip>` but to using the `<NavLink>` as the target element. It looks like binding to that is creating the unexpected behavior. If you assign the `id` to anything else, including a raw anchor element, it works as expected. I'd need to look at why `NavLink` does this while everything else works fine.

You could wrap the contents of the nav item with a `<span>` or assign the id to something else, and it'll work fine.

https://svelte.dev/repl/05710379976343ffa7777794cc34f771?version=4.2.12

**Comment by RoryDuncan** [comment]
This is a result of tooltips being accessible—aka showing on focus, right?
And NavLink is an <a> which is focus-able by default.

When you close the modal—the modal is destroyed—and focus returns to the link.

**Comment by dysfunc** [comment]
I thought that, but it works properly with raw anchor elements, which tells me it's isolated to the `<NavLink>`. I tried assigning the target `id` to  numerous elements and components and they all behave as expected when performing the same test.

**Comment by irt-msummers** [comment]
Thanks so much! I really appreciate it. I put the span around the NavItem instead of just around the Icon because in my case the tooltip was infringing too much on the Icon. Thought it was going to be a quick fix. Didn't mean to ruin a Saturday :)

**Comment by RoryDuncan** [comment]
> I thought that, but it works properly with raw anchor elements
Ooo, that made me curious. 

I tested that I could reproduce it with natively focusable elements. **Except** `<a>` without an `href` would not trigger it.

> https://svelte.dev/repl/d623df1c65014d9b895a201713fe3b3c?version=4.2.12

I believe this is all working as accessibly intended. You can use keyboard-only navigation to see this is a good interaction with a modal. The browser returns focus back to the element that opened a `<dialog>` or `role="dialog"`. You can turn the repl's `<Modal>` into a `<div>` and see it also causes the tooltip not to display when closed.

Which would mean the "fix" is to allow someone to opt-out of tooltips opening via `focus`, or as you suggested—add a non-focusable wrapper `<span>`.

**Comment by RoryDuncan** [comment]
No Saturdays ruined here @irt-msummers 😄. Was a fun exploration for me.

**Comment by dysfunc** [comment]
You didn't ruin anything. I appreciate you taking the time to report these things + have a discussion.

**Comment by dysfunc** [comment]
@RoryDuncan just realized my anchor test didn't have an href 🤦‍♂️
