### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by jamiegau** [sveltestrap/sveltestrap#77]
**Describe the bug**
I cannot obtain the `<input>` element instance from a `<Input>` when I `bind:this={InputElement}`

**How to reproduce**
create a typical page containing

```
<Input type="text" bind:value={newSetName}
 bind:this={InputElement}/>
```
After the page is loaded, I am trying to set focus on the <input> contained in the sveltestap implementation of <Input>
You would expect `inputElement.focus()` would work.  or `inputElement.element.focus()' however both approaches do not work.
I have been unable to find a workaround..  Apart from using a id tag and getting the element using that. UGLY

**Expected behavior**
to be able to reference the native element.

**Desktop (please complete the following information):**

- OS: MacOS latest.
- Browser Chrome latest
- Version SvelteStrap latest

**Comment by dysfunc** [comment]
I need to update the documentation, but this is a legacy issue from the previous repo. You can use the `inner` prop for the input to ref the input element. 

```svelte
<Input bind:inner={inputRef} ... />
```
