### ISSUE TITLE
Button with an href link breaks in svelte 5 🐛 

### ISSUE THREAD

**Issue by jonjes** [sveltestrap/sveltestrap#80]
The Sveltestrap version of a Button with an href link has a broken appearance in svelte 5. (Sveltestrap Button without an href link works fine, and a plain Bootstrap link button works fine in svelte 5.)

**How to reproduce**

1. Install a new svelte5 project from scratch and choose svelte5: `npm create svelte@latest`
2. Install sveltestrap: `npm install svelte @sveltestrap/sveltestrap`
3. Put the Bootstrap css styling to the app.html head section:
```
<head>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  />
</head>
```
4. In the routes/+page.svelte file, import the Button class, add one Button without an href link and a Button with one.
```
<script>
	import { Button } from '@sveltestrap/sveltestrap';
</script>

<div class="container">
	<h1>Welcome to SvelteKit</h1>
	<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

	<p class="pt-3">Sveltestrap "Without href" button is below:</p>
	<Button>Sveltestrap Without href</Button>

	<p class="pt-3">Sveltestrap "With href" button is below:</p>
	<Button href="/myLink">Sveltestrap With href</Button>

	<p class="pt-3">Plan Bootstrap "With href" is below:</p>
	<a class="btn btn-secondary" role="button" href="myLink">Bootstrap With href</a>
</div>
```

**Screenshot**

![image](https://github.com/sveltestrap/sveltestrap/assets/2365749/622032c0-9f48-4ff8-bcd9-2655b16bcb89)

**Desktop:**

- OS: ubuntu linux 24.04
- Browser: chrome, version 125
- Version: sveltestrap version 6.2.7

**Comment by dysfunc** [comment]
I'll at this, but you can directly include the styles using the <Style /> component as a workaround.

**Comment by dysfunc** [comment]
Since Svelte5 was a complete rewrite and they moved away from component classes, you'll need to enable legacy API support by updating your `compilerOptions` inside `svelte.config.js`. 

```js
export default {
  compilerOptions: {
    legacy: { 
      componentApi: true 
    }
  }
};
```

This makes Svelte < 5 components backwards compatible and allows you to continue to use Sveltestrap until the library can be updated to support the new API.
